"""MCP server for prolog-reasoner."""

from fastmcp import FastMCP

from prolog_reasoner.config import Settings
from prolog_reasoner.executor import PrologExecutor
from prolog_reasoner.llm_client import LLMClient
from prolog_reasoner.logger import SecureLogger, setup_logging
from prolog_reasoner.models import ExecutionRequest, TranslationRequest
from prolog_reasoner.reasoner import PrologReasoner
from prolog_reasoner.translator import PrologTranslator

logger = SecureLogger(__name__)


def create_reasoner() -> PrologReasoner:
    """Create and wire up the PrologReasoner with all dependencies.

    Reads configuration from environment variables, validates SWI-Prolog
    availability, and constructs the dependency graph.
    """
    settings = Settings()
    settings.validate_swipl()
    setup_logging(settings.log_level)

    llm_client = LLMClient(
        provider=settings.llm_provider,
        api_key=settings.llm_api_key,
        model=settings.llm_model,
        timeout_seconds=settings.llm_timeout_seconds,
    )
    translator = PrologTranslator(llm_client, settings)
    executor = PrologExecutor(settings)
    return PrologReasoner(translator, executor)


reasoner = create_reasoner()

mcp = FastMCP("prolog-reasoner")


@mcp.tool()
async def translate_to_prolog(
    query: str,
    context: str = "",
    max_corrections: int = 3,
) -> dict:
    """Translate natural language to Prolog code.

    Uses SWI-Prolog for syntax validation but does not execute the query.
    The generated code can be reviewed/modified before execution with
    execute_prolog.

    Args:
        query: Natural language logical question or facts.
        context: Additional premises or facts (natural language).
        max_corrections: Auto-correction attempts on syntax errors (0 to disable).
    """
    request = TranslationRequest(
        query=query,
        context=context,
        max_corrections=max_corrections,
    )
    result = await reasoner.translate(request)
    return result.model_dump()


@mcp.tool()
async def execute_prolog(
    prolog_code: str,
    query: str,
    max_results: int = 100,
) -> dict:
    """Execute Prolog code and return reasoning results.

    Runs code generated by translate_to_prolog or manually written Prolog.

    Args:
        prolog_code: Prolog code (facts and rules).
        query: Prolog query to execute (e.g. "mortal(X)").
        max_results: Maximum number of results (prevents infinite loops).
    """
    request = ExecutionRequest(
        prolog_code=prolog_code,
        query=query,
        max_results=max_results,
    )
    result = await reasoner.execute(request)
    return result.model_dump()


def main() -> None:
    """Entry point called from pyproject.toml [project.scripts]."""
    mcp.run()
